const today = new Date();

export const tasks = [
  
  // {//Preliminaries
  //   id: 100,
  //   text: "Preliminaries",
  //   type: "summary",
  //   parent: 0,
  //   open: false,
  //   start: today,
  //   end: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 15),
  //   duration: 15,
  // },
  // {
    
  //   id: 1,
  //   text: "Pre-Inspection (Checking of shaft)",
  //   type: "task",
  //   parent: 100,
  //   start: today,
  //   end: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 6),  
  //   duration: 6,  
  // },
  // {
  //   id: 2,
  //   text: "Layout of Drawing",
  //   type: "task",
  //   parent: 100,
  //   start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 6),
  //   duration: 3, 
  // },
  // {
  //   id: 3,
  //   text: "Submission of Drawing and Finishes for Approval",
  //   type: "task",
  //   parent: 100,
  //   start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 9), 
  //   duration: 5,
  // },
  // {
  //   id: 4,
  //   text: "Submission of PO to Factory",
  //   type: "task",
  //   parent: 100,
  //   start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 14), 
  //   duration: 1,
  // },

  // {//Structural/Civil Works
  //   id: 200,
  //   text: "Structural/Civil Works (Passenger Elevator)",
  //   type: "summary",
  //   parent: 0,
  //   open: false,
  //   start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 15), 
  //   end: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 90),
  //   duration: 75,
  // },
  // {
    
  //   id: 5,
  //   text: "Shaft Construction",
  //   type: "task",
  //   parent: 200,
  //   start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 15), 
  //   duration: 75,
  // },

  // {//Manufacturing and Importation Process of Passenger Elevator
  //   id: 300,
  //   text: "Manufacturing and Importation Process (Passenger Elevator)",
  //   type: "summary",
  //   parent: 0,
  //   open: false,
  //   start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 15), 
  //   end: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 90),
  //   duration: 75,
  // },
  // {
  //   id: 6,
  //   text: "Manufacturing and Importation",
  //   type: "task",
  //   parent: 300,
  //   start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 15), 
  //   duration: 75,
  // },

  // {//Planning for Mobilization and Execution
  //   id: 400,
  //   text: "Planning for Mobilization and Execution",
  //   type: "summary",
  //   parent: 0,
  //   open: false,
  //   start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 62), 
  //   end: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 82),
  //   duration: 20,
  // },
  // {
    
  //   id: 7,
  //   text: "Preparation of tools and materials for elevator installation",
  //   type: "task",
  //   parent: 400,
  //   start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 62), 
  //   duration: 14,
  // },
  // {
  //   id: 8,
  //   text: "Layout of boardup markings",
  //   type: "task",
  //   parent: 400,
  //   start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 76), 
  //   duration: 3,
  // },
  // {
  //   id: 9,
  //   text: "Partial delivery of tools and boardup materials",
  //   type: "task",
  //   parent: 400,
  //   start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 79), 
  //   duration: 3,
  // },

  {//Mechanical Installation
    id: 500,
    text: "Mechanical Installation (Passenger Elevator)",
    type: "summary",
    parent: 0,
    open: false,
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 90), 
    end: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 100),
    duration: 10,
  },
  {
    id: 10,
    text: "Unloading of elevator equipments",
    type: "task",
    parent: 500,
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 90), 
    duration: 1,
  },
  {
    id: 11,
    text: "Scaffolding Installation",
    type: "task",
    parent: 500,
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 91), 
    duration: 2,
  },
  {
    id: 12,
    text: "Hauling Works",
    type: "task",
    parent: 500,
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 93), 
    duration: 2,
  }, 
  {
    id: 13,
    text: "Template Setting",
    type: "task",
    parent: 500,
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 95), 
    duration: 2,
  },    
  {
    id: 14,
    text: "Marking and Boring of Holes",
    type: "task",
    parent: 500,
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 97), 
    duration: 1,
  },
  {
    id: 15,
    text: "Rail Bracket Installation",
    type: "task",
    parent: 500,
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 98), 
    duration: 2,
  },
  {
    id: 16,
    text: "Guide Rail Setting",
    type: "task",
    parent: 500,
    open: false,
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 100),
    end: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 105),
    duration: 5,
  },
  {
    id: 17,
    text: "Main/Car",
    type: "task",
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 100),
    duration: 2,
    parent: 16,
  },
  {
    id: 18,
    text: "Counterweight (CWT)",
    type: "task",
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 102),
    duration: 2,
    parent: 16,
  },
  {
    id: 19,
    text: "Gauging",
    type: "task",
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 104),
    duration: 1,
    parent: 16,
  },
  {
    id: 20,
    text: "Landing Door Assembly",
    type: "task",
    parent: 500,
    open: false,
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 105),
    end: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 111),
    duration: 6,
  },
  {
    id: 21,
    text: "Sills and Supports",
    type: "task",
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 105),
    duration: 2,
    parent: 20,
  },
  {
    id: 22,
    text: "Jamb and Supports",
    type: "task",
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 107),
    duration: 2,
    parent: 20,
  },
  {
    id: 23,
    text: "Frame and Doors",
    type: "task",
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 109),
    duration: 2,
    parent: 20,
  },
  {
    id: 24,
    text: "M/R Equipment Setting",
    type: "task",
    parent: 500,
    open: false,
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 111),
    end: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 117),
    duration: 6,
  },
  {
    id: 25,
    text: "Traction Machine",
    type: "task",
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 111),
    duration: 2,
    parent: 24,
  },
  {
    id: 26,
    text: "Support Beams",
    type: "task",
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 113),
    duration: 2,
    parent: 24,
  },
  {
    id: 27,
    text: "Governor",
    type: "task",
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 115),
    duration: 2,
    parent: 24,
  },
  {
    id: 28,
    text: "Installation of Control Panel",
    type: "task",
    parent: 500,
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 117),
    duration: 2,
  },
  {
    id: 29,
    text: "Car Assembly",
    type: "task",
    parent: 500,
    open: false,
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 119),
    end: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 122),
    duration: 3,
  },
  {
    id: 30,
    text: "All Accessories",
    type: "task",
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 119),
    duration: 2,
    parent: 29,
  },
  {
    id: 31,
    text: "Car Piping/Wiring",
    type: "task",
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 121),
    duration: 1,
    parent: 29,
  },
  {
    id: 32,
    text: "Travelling Cable Layout",
    type: "task",
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 122),
    parent: 500,
    duration: 2,
  },
  {
    id: 33,
    text: "Counterweight Assembly",
    type: "task",
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 124),
    parent: 500,
    duration: 2,
  },
  {
    id: 34,
    text: "Laying out of Ropes",
    type: "task",
    parent: 500,
    open: false,
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 126),
    end: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 131),
    duration: 5,
  },
  {
    id: 35,
    text: "Hoisting",
    type: "task",
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 126),
    duration: 2,
    parent: 34,
  },
  {
    id: 36,
    text: "Governor",
    type: "task",
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 128),
    duration: 2,
    parent: 34,
  },
  {
    id: 37,
    text: "Compensating",
    type: "task",
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 130),
    duration: 1,
    parent: 34,
  },
  {
    id: 38,
    text: "Wiring",
    type: "task",
    parent: 500,
    open: false,
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 131),
    end: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 133),
    duration: 2,
  },
  {
    id: 39,
    text: "Machine Room",
    type: "task",
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 131),
    duration: 1,
    parent: 38,
  },
  {
    id: 40,
    text: "Hoistway",
    type: "task",
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 132),
    duration: 1,
    parent: 38,
  },
  {
    id: 41,
    text: "Installation of Pit Ladder / Hoistway Lighting",
    type: "task",
    parent: 500,
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 133),
    duration: 2,
  },

  // Testing and Commissioning
  {
    id: 600,
    text: "Testing and Commissioning (Passenger Elevator)",
    type: "summary",
    parent: 0,
    open: false,
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 135),
    end: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 150),
    duration: 15,
  },
  {
    id: 42,
    text: "Initial testing",
    type: "task",
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 135),
    duration: 3,
    parent: 600,
  },
  {
    id: 43,
    text: "Slow speed",
    type: "task",
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 138),
    duration: 2,
    parent: 600,
  },
  {
    id: 44,
    text: "High speed and Mechanical Adjustment",
    type: "task",
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 140),
    duration: 2,
    parent: 600,
  },
  {
    id: 45,
    text: "Load Test",
    type: "task",
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 142),
    duration: 2,
    parent: 600,
  },
  {
    id: 46,
    text: "Final Adjust",
    type: "task",
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 144),
    duration: 2,
    parent: 600,
  },
  {
    id: 47,
    text: "Features Test / Correction of Defects",
    type: "task",
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 146),
    duration: 2,
    parent: 600,
  },
  {
    id: 48,
    text: "Final Cleaning / Hand over",
    type: "task",
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 148),
    duration: 2,
    parent: 600,
  },
];


export default {tasks};
